# obamaBot
def obamaBot():
    print("========================")
    print("*System: You are now connected with President Obama.")
    print(" ")
    time.sleep(delay)
    print("Obama: Hello! What is your name?")
    name = input("You: ").title()
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Obama: It's nice to meet you,",name,end="!\n")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Obama: Where are you from?")
    location = input("You: ").title()
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Obama: Wow! What a cool place, I wish I lived in",location,end=".\n")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Obama: Who is your favorite president?")
    print("*System: Type only the president's last name.")
    president = input("You: ").title()
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Obama: Good choice! President",president,"and I are best friends!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Obama: Did you know you have to be 35 years old to run for president?")
    time.sleep(delay)
    print("Obama: Speaking of running for president.. how old are you,",name,end="?\n")
    age = int(input("You: "))
    if age >= 35:
        print("Obama: Awesome! You're",age, "years old.", "You can run for president!")
    elif age < 35:
        print("Obama: Uh oh! You're",age, "years old.", "You can't run for president!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Obama: Anyways, It was nice meeting you good sir!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print(" ")
    print("*System: Chat session was ended by President Obama.")
    print("========================")

# chadBot
def chadBot():
    print("========================")
    print("*System: You are now connected with Chad.")
    print(" ")
    time.sleep(delay)    
    print("Chad: Aye! Whats yo name?")
    name = input("You: ").title()
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Chad: What up",name,end="\n")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Chad: Where you from bro?")
    location = input("You: ").title()
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Chad: Yoo! Dope place bruh, I wish I lived in",location,end=".\n")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Chad: How much do you lift bro?")
    print("*System: Chad can dead lift up to 250 lbs")
    lift = int(input("You: "))
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    if lift <= 249:
        print("Chad: What? That's it? Sissy.")
    elif lift > 250:
        print("Chad: Dayum! That's more than I can lift")
    elif lift == 250:
        print("Chad: Right on brother!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Chad: Favorite Wrestler. Go.")
    wrestler = input("You: ").title()
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Chad: Brah",wrestler,"like my favorite dude bro hells yeah!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Chad: Good seeing ya bro!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print(" ")
    print("*System: Chat session was ended by Chad")
    print("========================")    
    
# MomBot
def MomBot():
    print("========================")
    print("*System: You are now connected with your mother! (don't ask how)")
    print(" ")
    time.sleep(delay)    
    print("Mother Dearest: Hi sweetie how are you!!")
    mood = input("You: ").upper()
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("*System: An unexpected error has occured, we detect your mother has become angry.")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)    
    print("Mother Dearest: I DON'T CARE IF YOU ARE",mood,"GO CLEAN THE DISHES!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Mother Dearest: DID YOU FINISH YOUR HOMEWORK YET?!")
    print("*System: Say 1 or 2")
    print("1. Yes I did")
    print("2. No I didn't")
    int(input(">: "))
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Mother Dearest: YOU KNOW WHAT I DON'T EVEN CARE, YOU'RE GROUNDED!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Mother Dearest: DID YOU WALK THE DOG AT ALL!?")
    input("You: ")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Mother Dearest: ...Okay")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print("Mother Dearest: I'm sorry honey! I don't know what came over me. It's okay!")
    # Delay program (change using the "delay" variable)
    time.sleep(delay)
    print(" ")
    print("*System: Chat session was ended by your mother.")
    print("========================")
    

# Change this based on how you'd like the program to present
# If it's currently set to zero, they'll be no realistic delay between the bot's messages"
delay = 2

import time

print("Welcome to LonelyStrangers.com")
print("==============================")
print("System: Who would you like to talk to? (1, 2 or 3)")
print("1. Obama")
print("2. Chad")
print("3. Your Mom")
    
# Grab Input from the user
answer = input(">")
    
if answer == "1":
        obamaBot()
elif answer == "2":
        chadBot()
elif answer == "3":
        MomBot()
